<?php

return [
    'type_of_property' => 'По типу недвижимости',
    'street' => 'Улица',
    'type_of_activity' => 'По Виду деятельности',
    'except_type_of_activity' => 'Ограничения по Виду деятельности',
    'address_program' => 'Адрессная программа',
    'district' => 'Район',
    'metro' => 'Метро',
    'footage' => 'По площади (кв/м)',
    'budget_volume' => 'По бюджету',
    'budget_footage' => 'По бюджету за 1 кв/м в мес',
    'region' => 'Регион',
    'is_landlord' => 'С Арендаторами',
    'client_type' => 'Клиент',
    'near_metro' => 'Близость к метро',
    'income' => 'Предполагаемая доходность',
    'rent' => 'Предполагаемая Аренда в месяц., в рублях.',
    'payback_period' => 'Окупаемость мес.',
    'actual_payback' => 'Фактическая окупаемость',
    'payback_mpo' => 'Окупаемость МПО',
    'payback_yield' => 'Предполагаемый доходность',
    'actual_yield' => 'Фактическая доходность',
    'select_vip' => 'Локация VIP/Стандарт',
    'property_status' => 'Статус объекта',
    'address_program_send' => 'Рассылка клиентов только по адресным программам?',
    'except_companies' => 'Исключение компаний из выборки',
    'filter_companies' => 'Фильтр по компаниям'
];
